// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/team-nerd-planet/api-server/infra/config"
	"github.com/team-nerd-planet/api-server/infra/database"
	"github.com/team-nerd-planet/api-server/infra/database/repository"
	"github.com/team-nerd-planet/api-server/infra/router"
	"github.com/team-nerd-planet/api-server/internal/controller/rest"
	"github.com/team-nerd-planet/api-server/internal/usecase/item"
)

// Injectors from wire.go:

func InitServer() (router.Router, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return router.Router{}, err
	}
	databaseDatabase, err := database.NewDatabase(configConfig)
	if err != nil {
		return router.Router{}, err
	}
	itemRepo := repository.NewMemo(databaseDatabase)
	itemUsecase := item.NewItemUsecase(itemRepo)
	itemController := rest.NewItemController(itemUsecase)
	routerRouter := router.NewRouter(configConfig, itemController)
	return routerRouter, nil
}
